server:
  port: 8080

spring:
  application:
    name: esun-shopping-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/esun_shopping
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Taipei

cors:
  allowed-origins: http://localhost:5173